#!/usr/bin/env bash
# Manage script manage_my_process.
#   When pass argument `start`:
#     1. Start manage_my_process
#     2. Create file contain its PID in /var/run/my_process.pid
#     3. Display "manage_my_process started"
#   When pass argument `stop`:
#     1. Stop manage_my_process
#     2. Delete file /var/run/my_process.pid
#     3. Display "manage_my_process stopped"
#   When pass argument `restart`:
#     1. Stop manage_my_process
#     2. Delete file /var/run/my_process.pid
#     3. Start manage_my_process
#     4. Create file contain its PID IN /var/run/my_process.pid
#     5. Display "manage_my_process restarted"
#   If anything else or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"

if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
